// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcsfvellnwwyyyyuqtrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjc2Z2ZWxsbnd3eXl5eXVxdHJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDQyMTIsImV4cCI6MjA2NzI4MDIxMn0.dxpPj91Xv16yps8LTKO9mD_r99DDM_G-LQtupD4iEt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});